# Generated by Django 3.1.2 on 2020-10-25 14:31

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('googlemaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=100)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
            ],
        ),
    ]
